version: '2.1'
services:

######################################################
# DATABASE SERVICE
######################################################
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

    ports:
      - "32769:5432"
    #volumes:
      #- ./mnt/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
      #- PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "airflow_db", "-U", "airflow" ]
      timeout: 45s
      interval: 10s
      retries: 10

  adminer:
    image: wodby/adminer:latest
    container_name: adminer
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    ports:
      - "32767:9000"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=airflow_db
    healthcheck:
      test: [ "CMD", "nc", "-z", "adminer", "9000" ]
      timeout: 45s
      interval: 10s
      retries: 10

######################################################
# SPARK SERVICES
######################################################
  spark:
    build: ./docker/spark
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./mnt/airflow/dags:/opt/airflow/dags
    ports:
      - '8090:8080'
  spark-worker:
    build: ./docker/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./mnt/airflow/dags:/opt/airflow/dags
      

######################################################
# AIRFLOW
######################################################

  airflow:
    build: ./docker/airflow
    container_name: airflow
    volumes:
      - ./mnt/airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./mnt/airflow/dags:/opt/airflow/dags
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10

  telegraf:
    container_name: telegraf
    image: telegraf:1.12.3
    volumes:
      - ./mnt/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    container_name: influxdb
    image: influxdb:1.7.8
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ./mnt/influxdb:/var/lib/influxdb
    command: /bin/bash -c "/var/lib/influxdb/createdb.sh && /var/lib/influxdb/creatuser.sh"


  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./mnt/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000


  flask-web:
    build: ./docker/flask
    ports:
      - "5000:5000"
    command: python run.py
    volumes:
      - ./mnt/flask:/flask




######################################################
# NETWORK
######################################################

# Change name of default network otherwise URI invalid for HIVE
# because of the _ contained by default network
networks:
  default:
    name: airflow-network